// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RuleEngine.Infrastructure.Data;

#nullable disable

namespace RuleEngine.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RuleEngine.Domain.Entities.CreditAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Approved")
                        .HasColumnType("bit");

                    b.Property<Guid>("LoanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Observation")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("CreditAnalyses", (string)null);
                });

            modelBuilder.Entity("RuleEngine.Domain.Entities.CreditAnalysis", b =>
                {
                    b.OwnsOne("RuleEngine.Domain.Entities.Score", "Score", b1 =>
                        {
                            b1.Property<Guid>("CreditAnalysisId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Score_Description");

                            b1.Property<int>("Value")
                                .HasColumnType("int")
                                .HasColumnName("Score_Value");

                            b1.HasKey("CreditAnalysisId");

                            b1.ToTable("CreditAnalyses");

                            b1.WithOwner()
                                .HasForeignKey("CreditAnalysisId");
                        });

                    b.Navigation("Score")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
